package pocketwiki.pocketwiki.com.pocketwiki2.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "AUDIO_PATHS".
 */
public class AudioPaths {

    private Long audioPathId;
    private Long contentId;
    private Long languageId;
    private String audioPath;

    public AudioPaths() {
    }

    public AudioPaths(Long audioPathId) {
        this.audioPathId = audioPathId;
    }

    public AudioPaths(Long audioPathId, Long contentId, Long languageId, String audioPath) {
        this.audioPathId = audioPathId;
        this.contentId = contentId;
        this.languageId = languageId;
        this.audioPath = audioPath;
    }

    public Long getAudioPathId() {
        return audioPathId;
    }

    public void setAudioPathId(Long audioPathId) {
        this.audioPathId = audioPathId;
    }

    public Long getContentId() {
        return contentId;
    }

    public void setContentId(Long contentId) {
        this.contentId = contentId;
    }

    public Long getLanguageId() {
        return languageId;
    }

    public void setLanguageId(Long languageId) {
        this.languageId = languageId;
    }

    public String getAudioPath() {
        return audioPath;
    }

    public void setAudioPath(String audioPath) {
        this.audioPath = audioPath;
    }

}
