package pocketwiki.pocketwiki.com.pocketwiki2.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CATEGORY_ENTITIES".
 */
public class CategoryEntities {

    private Long categoryEntitiesId;
    private String createdAt;
    private String updatedAt;
    private Long categoryId;
    private Long entityId;

    public CategoryEntities() {
    }

    public CategoryEntities(Long categoryEntitiesId) {
        this.categoryEntitiesId = categoryEntitiesId;
    }

    public CategoryEntities(Long categoryEntitiesId, String createdAt, String updatedAt, Long categoryId, Long entityId) {
        this.categoryEntitiesId = categoryEntitiesId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.categoryId = categoryId;
        this.entityId = entityId;
    }

    public Long getCategoryEntitiesId() {
        return categoryEntitiesId;
    }

    public void setCategoryEntitiesId(Long categoryEntitiesId) {
        this.categoryEntitiesId = categoryEntitiesId;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    public Long getEntityId() {
        return entityId;
    }

    public void setEntityId(Long entityId) {
        this.entityId = entityId;
    }

}
