package pocketwiki.pocketwiki.com.pocketwiki2.Dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import pocketwiki.pocketwiki.com.pocketwiki2.Dao.CityDao;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.AreaDao;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.SubEntityDao;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.EntityDao;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.CategoryDao;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.LanguageDao;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.AreaEntitiesDao;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.CategoryEntitiesDao;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.ContentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        CityDao.createTable(db, ifNotExists);
        AreaDao.createTable(db, ifNotExists);
        SubEntityDao.createTable(db, ifNotExists);
        EntityDao.createTable(db, ifNotExists);
        CategoryDao.createTable(db, ifNotExists);
        LanguageDao.createTable(db, ifNotExists);
        AreaEntitiesDao.createTable(db, ifNotExists);
        CategoryEntitiesDao.createTable(db, ifNotExists);
        ContentDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        CityDao.dropTable(db, ifExists);
        AreaDao.dropTable(db, ifExists);
        SubEntityDao.dropTable(db, ifExists);
        EntityDao.dropTable(db, ifExists);
        CategoryDao.dropTable(db, ifExists);
        LanguageDao.dropTable(db, ifExists);
        AreaEntitiesDao.dropTable(db, ifExists);
        CategoryEntitiesDao.dropTable(db, ifExists);
        ContentDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(CityDao.class);
        registerDaoClass(AreaDao.class);
        registerDaoClass(SubEntityDao.class);
        registerDaoClass(EntityDao.class);
        registerDaoClass(CategoryDao.class);
        registerDaoClass(LanguageDao.class);
        registerDaoClass(AreaEntitiesDao.class);
        registerDaoClass(CategoryEntitiesDao.class);
        registerDaoClass(ContentDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
