package pocketwiki.pocketwiki.com.pocketwiki2.Dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import pocketwiki.pocketwiki.com.pocketwiki2.Dao.City;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.Area;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.SubEntity;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.Entity;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.Category;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.Language;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.AreaEntities;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.CategoryEntities;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.Content;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.AudioPaths;

import pocketwiki.pocketwiki.com.pocketwiki2.Dao.CityDao;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.AreaDao;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.SubEntityDao;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.EntityDao;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.CategoryDao;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.LanguageDao;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.AreaEntitiesDao;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.CategoryEntitiesDao;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.ContentDao;
import pocketwiki.pocketwiki.com.pocketwiki2.Dao.AudioPathsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityDaoConfig;
    private final DaoConfig areaDaoConfig;
    private final DaoConfig subEntityDaoConfig;
    private final DaoConfig entityDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig languageDaoConfig;
    private final DaoConfig areaEntitiesDaoConfig;
    private final DaoConfig categoryEntitiesDaoConfig;
    private final DaoConfig contentDaoConfig;
    private final DaoConfig audioPathsDaoConfig;

    private final CityDao cityDao;
    private final AreaDao areaDao;
    private final SubEntityDao subEntityDao;
    private final EntityDao entityDao;
    private final CategoryDao categoryDao;
    private final LanguageDao languageDao;
    private final AreaEntitiesDao areaEntitiesDao;
    private final CategoryEntitiesDao categoryEntitiesDao;
    private final ContentDao contentDao;
    private final AudioPathsDao audioPathsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        areaDaoConfig = daoConfigMap.get(AreaDao.class).clone();
        areaDaoConfig.initIdentityScope(type);

        subEntityDaoConfig = daoConfigMap.get(SubEntityDao.class).clone();
        subEntityDaoConfig.initIdentityScope(type);

        entityDaoConfig = daoConfigMap.get(EntityDao.class).clone();
        entityDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        languageDaoConfig = daoConfigMap.get(LanguageDao.class).clone();
        languageDaoConfig.initIdentityScope(type);

        areaEntitiesDaoConfig = daoConfigMap.get(AreaEntitiesDao.class).clone();
        areaEntitiesDaoConfig.initIdentityScope(type);

        categoryEntitiesDaoConfig = daoConfigMap.get(CategoryEntitiesDao.class).clone();
        categoryEntitiesDaoConfig.initIdentityScope(type);

        contentDaoConfig = daoConfigMap.get(ContentDao.class).clone();
        contentDaoConfig.initIdentityScope(type);

        audioPathsDaoConfig = daoConfigMap.get(AudioPathsDao.class).clone();
        audioPathsDaoConfig.initIdentityScope(type);

        cityDao = new CityDao(cityDaoConfig, this);
        areaDao = new AreaDao(areaDaoConfig, this);
        subEntityDao = new SubEntityDao(subEntityDaoConfig, this);
        entityDao = new EntityDao(entityDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        languageDao = new LanguageDao(languageDaoConfig, this);
        areaEntitiesDao = new AreaEntitiesDao(areaEntitiesDaoConfig, this);
        categoryEntitiesDao = new CategoryEntitiesDao(categoryEntitiesDaoConfig, this);
        contentDao = new ContentDao(contentDaoConfig, this);
        audioPathsDao = new AudioPathsDao(audioPathsDaoConfig, this);

        registerDao(City.class, cityDao);
        registerDao(Area.class, areaDao);
        registerDao(SubEntity.class, subEntityDao);
        registerDao(Entity.class, entityDao);
        registerDao(Category.class, categoryDao);
        registerDao(Language.class, languageDao);
        registerDao(AreaEntities.class, areaEntitiesDao);
        registerDao(CategoryEntities.class, categoryEntitiesDao);
        registerDao(Content.class, contentDao);
        registerDao(AudioPaths.class, audioPathsDao);
    }
    
    public void clear() {
        cityDaoConfig.getIdentityScope().clear();
        areaDaoConfig.getIdentityScope().clear();
        subEntityDaoConfig.getIdentityScope().clear();
        entityDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        languageDaoConfig.getIdentityScope().clear();
        areaEntitiesDaoConfig.getIdentityScope().clear();
        categoryEntitiesDaoConfig.getIdentityScope().clear();
        contentDaoConfig.getIdentityScope().clear();
        audioPathsDaoConfig.getIdentityScope().clear();
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public AreaDao getAreaDao() {
        return areaDao;
    }

    public SubEntityDao getSubEntityDao() {
        return subEntityDao;
    }

    public EntityDao getEntityDao() {
        return entityDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public LanguageDao getLanguageDao() {
        return languageDao;
    }

    public AreaEntitiesDao getAreaEntitiesDao() {
        return areaEntitiesDao;
    }

    public CategoryEntitiesDao getCategoryEntitiesDao() {
        return categoryEntitiesDao;
    }

    public ContentDao getContentDao() {
        return contentDao;
    }

    public AudioPathsDao getAudioPathsDao() {
        return audioPathsDao;
    }

}
