package pocketwiki.pocketwiki.com.pocketwiki2.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LANGUAGE".
 */
public class Language {

    private Long languageId;
    private String createdAt;
    private String updatedAt;
    private String name;
    private Boolean defaultLanguageFlag;

    public Language() {
    }

    public Language(Long languageId) {
        this.languageId = languageId;
    }

    public Language(Long languageId, String createdAt, String updatedAt, String name, Boolean defaultLanguageFlag) {
        this.languageId = languageId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.name = name;
        this.defaultLanguageFlag = defaultLanguageFlag;
    }

    public Long getLanguageId() {
        return languageId;
    }

    public void setLanguageId(Long languageId) {
        this.languageId = languageId;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getDefaultLanguageFlag() {
        return defaultLanguageFlag;
    }

    public void setDefaultLanguageFlag(Boolean defaultLanguageFlag) {
        this.defaultLanguageFlag = defaultLanguageFlag;
    }

}
