package pocketwiki.pocketwiki.com.pocketwiki2.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SUB_ENTITY".
 */
public class SubEntity {

    private Long subEntityId;
    private String createdAt;
    private String updatedAt;
    private String name;
    private Long entityId;
    private String imageURLThumb;
    private String imageURLLarge;
    private String imageURLThumbOnline;
    private String imageURLLargeOnline;

    public SubEntity() {
    }

    public SubEntity(Long subEntityId) {
        this.subEntityId = subEntityId;
    }

    public SubEntity(Long subEntityId, String createdAt, String updatedAt, String name, Long entityId, String imageURLThumb, String imageURLLarge, String imageURLThumbOnline, String imageURLLargeOnline) {
        this.subEntityId = subEntityId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.name = name;
        this.entityId = entityId;
        this.imageURLThumb = imageURLThumb;
        this.imageURLLarge = imageURLLarge;
        this.imageURLThumbOnline = imageURLThumbOnline;
        this.imageURLLargeOnline = imageURLLargeOnline;
    }

    public Long getSubEntityId() {
        return subEntityId;
    }

    public void setSubEntityId(Long subEntityId) {
        this.subEntityId = subEntityId;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getEntityId() {
        return entityId;
    }

    public void setEntityId(Long entityId) {
        this.entityId = entityId;
    }

    public String getImageURLThumb() {
        return imageURLThumb;
    }

    public void setImageURLThumb(String imageURLThumb) {
        this.imageURLThumb = imageURLThumb;
    }

    public String getImageURLLarge() {
        return imageURLLarge;
    }

    public void setImageURLLarge(String imageURLLarge) {
        this.imageURLLarge = imageURLLarge;
    }

    public String getImageURLThumbOnline() {
        return imageURLThumbOnline;
    }

    public void setImageURLThumbOnline(String imageURLThumbOnline) {
        this.imageURLThumbOnline = imageURLThumbOnline;
    }

    public String getImageURLLargeOnline() {
        return imageURLLargeOnline;
    }

    public void setImageURLLargeOnline(String imageURLLargeOnline) {
        this.imageURLLargeOnline = imageURLLargeOnline;
    }

}
